# Generated by Django 4.0.6 on 2023-03-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('messages', models.JSONField(default={'state': 0})),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=128, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('menu', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
