# Generated by Django 4.0.6 on 2023-03-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lang',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
