# Generated by Django 4.0.6 on 2023-03-10 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_user_lang_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='first_name',
        ),
    ]
